# Generated by Django 5.1.7 on 2025-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_created_by_company_industry_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
