# Generated by Django 5.1.7 on 2025-06-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_individual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
